### ISSUE TITLE
Set CSP Header into JAVA_OPTS environment variable failed

### ISSUE THREAD

**Issue by jmejia32** [bitnami/bitnami-docker-jenkins#77]
### Name and Version

bitnami/jenkins:2.303.3

### What steps will reproduce the bug?

1. Execute `docker compose up -d` in terminal.
2. Container doesn't start

### What is the expected behavior?

Jenkins initialisation completed

### What do you see instead?

Logs from bitnami container

```
app_stack-jenkins-1  | jenkins 20:57:03.95 Welcome to the Bitnami jenkins container
app_stack-jenkins-1  | jenkins 20:57:03.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
app_stack-jenkins-1  | jenkins 20:57:03.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
app_stack-jenkins-1  | jenkins 20:57:03.96 
app_stack-jenkins-1  | jenkins 20:57:03.96 INFO  ==> ** Starting Jenkins setup **
app_stack-jenkins-1  | jenkins 20:57:04.02 INFO  ==> Detected data from previous deployments
app_stack-jenkins-1  | jenkins 20:57:04.02 INFO  ==> ** Jenkins setup finished! **
app_stack-jenkins-1  | 
app_stack-jenkins-1  | jenkins 20:57:04.05 INFO  ==> ** Starting Jenkins **
app_stack-jenkins-1  | Error: Could not find or load main class allow-same-origin;
```

### Additional information

`docker-compose.yml` used

```yaml
version: "3.7"
services:
  jenkins:
    build:
      context: ./jenkins
    restart: always
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
    environment:
      JAVA_OPTS: >-
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"
volumes:
  jenkins_data:
    driver: local
```

`Dockerfile` inside context

```Dockerfile
FROM bitnami/jenkins:2.303.3

USER 0
ARG JENKINS_DIR=/usr/share/jenkins/ref
RUN mkdir -p ${JENKINS_DIR}/plugins
WORKDIR ${JENKINS_DIR}

RUN curl -LO https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.11.1/jenkins-plugin-manager-2.11.1.jar
COPY plugins.yaml .

ARG CACHE_DIR=${JENKINS_DIR}/.cache/jenkins-plugin-management-cli
RUN mkdir -p ${CACHE_DIR}

RUN env CACHE_DIR=${CACHE_DIR} java -jar jenkins-plugin-manager-*.jar -w /opt/bitnami/jenkins/jenkins.war -f ${JENKINS_DIR}/plugins.yaml -d plugins

WORKDIR /
USER 1001
```

**Comment by juan131** [comment]
Hi @jmejia32 

It doesn't look to me like an issue with the Bitnami Jenkins container image but a consequence of the customizations you added on top of it.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by jmejia32** [comment]
Hi, @juan131 . Recently I have tested this again but without Dockerfile (I mean, original image from Docker Hub, no customizations) and results are the same.

docker-compose.yml:
```yml
version: '2'
services:
  jenkins:
    image: docker.io/bitnami/jenkins:2.319.3
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
    environment:
      JAVA_OPTS: >-
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"
volumes:
  jenkins_data:
    driver: local
```

Logs:
```
id_jenkins-jenkins-1  | jenkins 16:51:18.21 
id_jenkins-jenkins-1  | jenkins 16:51:18.21 Welcome to the Bitnami jenkins container
id_jenkins-jenkins-1  | jenkins 16:51:18.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
id_jenkins-jenkins-1  | jenkins 16:51:18.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
id_jenkins-jenkins-1  | jenkins 16:51:18.21 
id_jenkins-jenkins-1  | jenkins 16:51:18.28 INFO  ==> Configuring libnss_wrapper
id_jenkins-jenkins-1  | jenkins 16:51:18.31 INFO  ==> ** Starting Jenkins setup **
id_jenkins-jenkins-1  | jenkins 16:51:18.38 INFO  ==> Detected data from previous deployments
id_jenkins-jenkins-1  | jenkins 16:51:18.38 INFO  ==> ** Jenkins setup finished! **
id_jenkins-jenkins-1  | 
id_jenkins-jenkins-1  | jenkins 16:51:18.40 INFO  ==> ** Starting Jenkins **
id_jenkins-jenkins-1  | Error: Could not find or load main class allow-scripts
id_jenkins-jenkins-1 exited with code 1
```

**Comment by juan131** [comment]
Hi @jmejia32 

I think the issue is that your custom JAVA opts are trying to load a class implemented in a JAR that isn't included in the Jenkins image, see:

```
Error: Could not find or load main class allow-scripts
```

**Comment by jmejia32** [comment]
@juan131 buddy, It isn't about java classes hahaha... It's about configuring Content Security Policy header inside Jenkins. The main goal is described [here](https://issues.jenkins.io/browse/JENKINS-32118?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel).

They provided a way via Scripting Console but i'll need to execute that command every time Jenkins restarts. I need to do this permanently, that's why I dediced to do it via `JAVA_OPTS` environment variable.

**Comment by jmejia32** [comment]
@juan131 it seems the sh inital scripts of the container strips the string value of the environment variable and when it's passed to java arguments causes the error previously indicated.

**Comment by juan131** [comment]
Hi @jmejia32 

In the links below you can find more information about how JAVA_OPTS are passed as arguments to the "java" command:

- https://github.com/bitnami/bitnami-docker-jenkins#passing-jvm-parameters
- https://github.com/bitnami/bitnami-docker-jenkins/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/jenkins/run.sh#L18

> it seems the sh initial scripts of the container strips the string value of the environment variable and when it's passed to java arguments causes the error previously indicated

Have you tried to escape characters to avoid them to be stripped?

> @juan131 buddy, It isn't about java classes hahaha.

Please note this kind of comments are against this project's [Code of Conduct](https://github.com/bitnami/bitnami-docker-jenkins/blob/master/CODE_OF_CONDUCT.md). Please consider this a warning.

**Comment by jmejia32** [comment]
Ok @juan131, let me show you the value of environment variable inside the container:

`docker-compose.yml` used:
```yml
version: '2'
services:
  jenkins:
    image: docker.io/bitnami/jenkins:2.319.3
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
    environment:
      JAVA_OPTS1: >-
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"
volumes:
  jenkins_data:
    driver: local
```

```sh
$ docker compose exec -T jenkins env | grep -i JAVA_OPTS
```

Command Output:
```
JAVA_OPTS1=-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"

```

So as you can see, the variable is displayed as it is defined in `docker-compose.yml`file. Please, consider to check out this issue thoroughly.

**Comment by juan131** [comment]
Hi @jmejia32 

I identified the issue.

The logic is not recognizing `-Dhudson.model.DirectoryBrowserSupport.CSP` as the "key" and `"sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"` as the "value".

This is splitting the whole string by spaces:

```bash
read -r -a java_opts <<< "$JAVA_OPTS"
```

Therefore, the `java_opts` array is created like this:

```console
$ echo "${java_opts[@]}"
-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin; allow-scripts; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ;"
$ echo "${java_opts[0]}"
-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox
$ echo "${java_opts[1]}"
allow-same-origin;
$ echo "${java_opts[2]}"
allow-scripts;
$ echo "${java_opts[3]}"
default-src
$ echo "${java_opts[4]}"
'none';
...
```

**Comment by jmejia32** [comment]
@juan131 Ok, I got it. The issue is related exclusively to space characters, pretty difficult.

My question is: Is there a alternative way to achieve my goal? Groovy script at Jenkins start up maybe?

**Comment by juan131** [comment]
In other Bitnami containers (unfortunately not in Jenkins yet) we provide the possibility of mounting custom scripts that are executed after initializing the application. For instance, check MariaDB:

- https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance

Would sth like this work for you? I mean, providing a way to mount your custom Groovy scripts so they're recognized and automatically executed after initializing Jenkins.

**Comment by jmejia32** [comment]
Yes, definitively. So, I tried mounting a groovy file into init.groovy.d directory in container like this:

```yaml
version: '2'
services:
  jenkins:
    image: docker.io/bitnami/jenkins:2.319.3
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - './csp_header.groovy:/bitnami/jenkins/home/init.groovy.d/csp_header.groovy:ro'
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF8"
volumes:
  jenkins_data:
    driver: local
```

`csp_header.groovy`
```groovy
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-scripts allow-same-origin; default-src 'none'; img-src 'self' data: ; style-src 'self' 'unsafe-inline' data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval';");
println " [custom-groovy-script-init] CSP Header set"
```

Logs:
```
id_jenkins-jenkins-1  | 2022-02-22 04:05:45.447+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
id_jenkins-jenkins-1  | 2022-02-22 04:05:51.036+0000 [id=35]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
id_jenkins-jenkins-1  | 2022-02-22 04:05:51.058+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
id_jenkins-jenkins-1  | 2022-02-22 04:05:51.069+0000 [id=41]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.407+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.409+0000 [id=39]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.496+0000 [id=42]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.497+0000 [id=36]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.504+0000 [id=36]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /bitnami/jenkins/home/init.groovy.d/csp_header.groovy
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.569+0000 [id=59]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.574+0000 [id=59]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 3 ms
id_jenkins-jenkins-1  |  [custom-groovy-script-init] CSP Header set
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.756+0000 [id=36]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
id_jenkins-jenkins-1  | 2022-02-22 04:05:52.782+0000 [id=22]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

This configuration worked for me.

**Comment by juan131** [comment]
Awesome @jmejia32 ! Could you please give a try to the solution I proposed at https://github.com/bitnami/bitnami-docker-jenkins/pull/79?

**Comment by jmejia32** [comment]
@juan131 Sure. I will try later.

**Comment by juan131** [comment]
@jmejia32 you can simply clone the repo and checkout to the "custom-scripts" branch that includes my changes, see:

- https://github.com/bitnami/bitnami-docker-jenkins/tree/custom-scripts

**Comment by jmejia32** [comment]
Recently I tested it out and results aren't succesful.

Script to create local image
```sh
$ docker build -t bitnami/jenkins:2.319-custom-scripts 'https://github.com/bitnami/bitnami-docker-jenkins.git#custom-scripts:2/debian-10'
```

`docker-compose.yml` used:
```yml
version: '2'
services:
  jenkins:
    image: bitnami/jenkins:2.319-custom-scripts
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - './csp_header.groovy:/docker-entrypoint-initdb.d/csp_header.groovy:ro'
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF8"
volumes:
  jenkins_data:
    driver: local
```
Logs
```console
$ docker compose up -d && docker compose logs -ft --tail 50
[+] Running 3/3
 ⠿ Network jenkins-test_default        C...                                0.1s
 ⠿ Volume "jenkins-test_jenkins_data"  Created                             0.0s
 ⠿ Container jenkins-test-jenkins-1    Started                             0.6s
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.101529015Z jenkins 19:54:32.10 
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.102935234Z jenkins 19:54:32.10 Welcome to the Bitnami jenkins container
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.104643433Z jenkins 19:54:32.10 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.105950405Z jenkins 19:54:32.10 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.107716251Z jenkins 19:54:32.10 
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.115311689Z jenkins 19:54:32.11 INFO  ==> Configuring libnss_wrapper
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.129021096Z jenkins 19:54:32.12 INFO  ==> ** Starting Jenkins setup **
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.294902259Z realpath: /usr/share/jenkins/ref: No such file or directory
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.297158995Z jenkins 19:54:32.29 INFO  ==> Creating init script
jenkins-test-jenkins-1  | 2022-02-26T19:54:32.309789472Z jenkins 19:54:32.30 INFO  ==> Starting Jenkins in background
jenkins-test-jenkins-1  | 2022-02-26T19:55:22.382911630Z jenkins 19:55:22.38 INFO  ==> Stopping Jenkins
jenkins-test-jenkins-1  | 2022-02-26T19:55:23.435774054Z jenkins 19:55:23.43 INFO  ==> ** Jenkins setup finished! **
jenkins-test-jenkins-1  | 2022-02-26T19:55:23.435793081Z 
jenkins-test-jenkins-1  | 2022-02-26T19:55:23.471180270Z jenkins 19:55:23.47 INFO  ==> ** Starting Jenkins **
jenkins-test-jenkins-1  | 2022-02-26T19:55:23.874423614Z Running from: /opt/bitnami/jenkins/jenkins.war
jenkins-test-jenkins-1  | 2022-02-26T19:55:23.970311964Z webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.220610389Z 2022-02-26 19:55:24.194+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @715ms to org.eclipse.jetty.util.log.JavaUtilLog
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.318054014Z 2022-02-26 19:55:24.317+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.368964097Z 2022-02-26 19:55:24.368+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.471609383Z 2022-02-26 19:55:24.471+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_322-b06
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.867087195Z 2022-02-26 19:55:24.866+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.942843410Z 2022-02-26 19:55:24.942+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.943084183Z 2022-02-26 19:55:24.942+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
jenkins-test-jenkins-1  | 2022-02-26T19:55:24.945180673Z 2022-02-26 19:55:24.944+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
jenkins-test-jenkins-1  | 2022-02-26T19:55:25.541324601Z 2022-02-26 19:55:25.540+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /bitnami/jenkins/home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins-test-jenkins-1  | 2022-02-26T19:55:25.693120597Z 2022-02-26 19:55:25.692+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@cd1e646{Jenkins v2.319.3,/,file:///bitnami/jenkins/home/war/,AVAILABLE}{/bitnami/jenkins/home/war}
jenkins-test-jenkins-1  | 2022-02-26T19:55:25.735646818Z 2022-02-26 19:55:25.734+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@3a03464{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
jenkins-test-jenkins-1  | 2022-02-26T19:55:25.736566498Z 2022-02-26 19:55:25.735+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @2257ms
jenkins-test-jenkins-1  | 2022-02-26T19:55:25.738346905Z 2022-02-26 19:55:25.737+0000 [id=22]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
jenkins-test-jenkins-1  | 2022-02-26T19:55:28.208628198Z 2022-02-26 19:55:28.204+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
jenkins-test-jenkins-1  | 2022-02-26T19:55:28.528930301Z 2022-02-26 19:55:28.528+0000 [id=31]	WARNING	hudson.ClassicPluginStrategy#createPluginWrapper: encountered /bitnami/jenkins/home/plugins/swarm-3.22.jpi under a nonstandard name; expected swarm.jpi
jenkins-test-jenkins-1  | 2022-02-26T19:55:28.589374102Z 2022-02-26 19:55:28.588+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
jenkins-test-jenkins-1  | 2022-02-26T19:55:34.819029453Z 2022-02-26 19:55:34.818+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
jenkins-test-jenkins-1  | 2022-02-26T19:55:34.884828014Z 2022-02-26 19:55:34.884+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
jenkins-test-jenkins-1  | 2022-02-26T19:55:34.916942225Z 2022-02-26 19:55:34.916+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.592413124Z 2022-02-26 19:55:36.592+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.593904000Z 2022-02-26 19:55:36.593+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.605355650Z 2022-02-26 19:55:36.605+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.610095352Z 2022-02-26 19:55:36.609+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.694980072Z 2022-02-26 19:55:36.682+0000 [id=47]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.717117037Z 2022-02-26 19:55:36.714+0000 [id=47]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 20 ms
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.814783631Z 2022-02-26 19:55:36.814+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
jenkins-test-jenkins-1  | 2022-02-26T19:55:36.840804692Z 2022-02-26 19:55:36.840+0000 [id=21]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

**Comment by jmejia32** [comment]
@juan131, recently I tested it out and results aren't successful

Image built with this command ([reference](https://github.com/bitnami/bitnami-docker-jenkins#get-this-image)):
```sh
$ docker build -t bitnami/jenkins:2.319-custom-scripts 'https://github.com/bitnami/bitnami-docker-jenkins.git#custom-scripts:2/debian-10'
```

`docker-compose.yml` used for this test:
```yaml
version: '2'
services:
  jenkins:
    image: bitnami/jenkins:2.319-custom-scripts
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - './csp_header.groovy:/docker-entrypoint-initdb.d/csp_header.groovy:ro'
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF8"
volumes:
  jenkins_data:
    driver: local
```

Logs
```console
$ docker compose up -d && docker compose logs -ft --tail 50
[+] Running 3/3
 ⠿ Network jenkins-test_default        Created                                                                                                                                              0.1s
 ⠿ Volume "jenkins-test_jenkins_data"  Created                                                                                                                                              0.0s
 ⠿ Container jenkins-test-jenkins-1    Started                                                                                                                                              0.8s
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.415659404Z jenkins 19:36:28.41 
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.417067063Z jenkins 19:36:28.41 Welcome to the Bitnami jenkins container
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.418424194Z jenkins 19:36:28.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.419736487Z jenkins 19:36:28.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.421217554Z jenkins 19:36:28.42 
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.428097400Z jenkins 19:36:28.42 INFO  ==> Configuring libnss_wrapper
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.438505391Z jenkins 19:36:28.43 INFO  ==> ** Starting Jenkins setup **
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.620615781Z realpath: /usr/share/jenkins/ref: No such file or directory
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.622892163Z jenkins 19:36:28.62 INFO  ==> Creating init script
jenkins-test-jenkins-1  | 2022-02-27T19:36:28.637479317Z jenkins 19:36:28.63 INFO  ==> Starting Jenkins in background
jenkins-test-jenkins-1  | 2022-02-27T19:37:18.714205599Z jenkins 19:37:18.71 INFO  ==> Stopping Jenkins
jenkins-test-jenkins-1  | 2022-02-27T19:37:19.741891246Z jenkins 19:37:19.74 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
jenkins-test-jenkins-1  | 2022-02-27T19:37:19.748651982Z jenkins 19:37:19.74 INFO  ==> Starting Jenkins in background
jenkins-test-jenkins-1  | 2022-02-27T19:37:39.766566527Z jenkins 19:37:39.76 INFO  ==> Stopping Jenkins
jenkins-test-jenkins-1  | 2022-02-27T19:37:40.808655401Z touch: cannot touch '/bitnami/jenkins/.user_scripts_initialized': Permission denied
jenkins-test-jenkins-1 exited with code 1
```

**Comment by juan131** [comment]
Sorry @jmejia32 

I forgot to provide write permissions in that folder.. I just updated the branch with a new commit, could you retry?

**Comment by jmejia32** [comment]
@juan131 Yes, I tried it again and... It seems the script wasn't executed correctly.

Logs:
```console
$ docker compose up -d && docker compose logs -f --tail 50                                                                               
[+] Running 3/3
 ⠿ Network id_jenkins_default        Created                                                                                                                                                                                                                               0.3s
 ⠿ Volume "id_jenkins_jenkins_data"  Created                                                                                                                                                                                                                               0.1s
 ⠿ Container id_jenkins-jenkins-1    Started                                                                                                                                                                                                                               3.5s
id_jenkins-jenkins-1  | jenkins 16:18:07.94 
id_jenkins-jenkins-1  | jenkins 16:18:07.94 Welcome to the Bitnami jenkins container
id_jenkins-jenkins-1  | jenkins 16:18:07.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
id_jenkins-jenkins-1  | jenkins 16:18:07.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
id_jenkins-jenkins-1  | jenkins 16:18:07.94 
id_jenkins-jenkins-1  | jenkins 16:18:07.94 INFO  ==> Configuring libnss_wrapper
id_jenkins-jenkins-1  | jenkins 16:18:07.95 INFO  ==> ** Starting Jenkins setup **
id_jenkins-jenkins-1  | realpath: /usr/share/jenkins/ref: No such file or directory
id_jenkins-jenkins-1  | jenkins 16:18:08.02 INFO  ==> Creating init script
id_jenkins-jenkins-1  | jenkins 16:18:08.03 INFO  ==> Starting Jenkins in background
id_jenkins-jenkins-1  | jenkins 16:18:38.27 INFO  ==> Stopping Jenkins
id_jenkins-jenkins-1  | jenkins 16:18:39.33 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
id_jenkins-jenkins-1  | jenkins 16:18:39.37 INFO  ==> Starting Jenkins in background
id_jenkins-jenkins-1  | jenkins 16:18:49.42 INFO  ==> Stopping Jenkins
id_jenkins-jenkins-1  | 
id_jenkins-jenkins-1  | jenkins 16:18:50.47 INFO  ==> ** Jenkins setup finished! **
id_jenkins-jenkins-1  | jenkins 16:18:50.54 INFO  ==> ** Starting Jenkins **
id_jenkins-jenkins-1  | Running from: /opt/bitnami/jenkins/jenkins.war
id_jenkins-jenkins-1  | webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
id_jenkins-jenkins-1  | 2022-03-01 16:18:50.856+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @306ms to org.eclipse.jetty.util.log.JavaUtilLog
id_jenkins-jenkins-1  | 2022-03-01 16:18:50.909+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
id_jenkins-jenkins-1  | 2022-03-01 16:18:50.930+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
id_jenkins-jenkins-1  | 2022-03-01 16:18:50.973+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_322-b06
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.130+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.154+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.154+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.155+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.373+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /bitnami/jenkins/home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.429+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@cd1e646{Jenkins v2.319.3,/,file:///bitnami/jenkins/home/war/,AVAILABLE}{/bitnami/jenkins/home/war}
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.439+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@3a03464{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.439+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @890ms
id_jenkins-jenkins-1  | 2022-03-01 16:18:51.440+0000 [id=23]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
id_jenkins-jenkins-1  | 2022-03-01 16:18:52.308+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
id_jenkins-jenkins-1  | 2022-03-01 16:18:52.365+0000 [id=43]	WARNING	hudson.ClassicPluginStrategy#createPluginWrapper: encountered /bitnami/jenkins/home/plugins/swarm-3.22.jpi under a nonstandard name; expected swarm.jpi
id_jenkins-jenkins-1  | 2022-03-01 16:18:52.424+0000 [id=45]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
id_jenkins-jenkins-1  | 2022-03-01 16:18:55.298+0000 [id=51]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
id_jenkins-jenkins-1  | 2022-03-01 16:18:55.304+0000 [id=46]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
id_jenkins-jenkins-1  | 2022-03-01 16:18:55.309+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.065+0000 [id=49]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.066+0000 [id=49]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.069+0000 [id=37]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.069+0000 [id=36]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.075+0000 [id=64]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.084+0000 [id=64]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 9 ms
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.151+0000 [id=42]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
id_jenkins-jenkins-1  | 2022-03-01 16:18:56.208+0000 [id=22]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

In logs doesn't appear the text `[custom-groovy-script-init] CSP Header set`. In Jenkins' script console, isn't reflected the new property.

![image](https://user-images.githubusercontent.com/15973840/156208996-027bbc2c-8440-44ec-b61d-999578cc6a33.png)

**Comment by jmejia32** [comment]
@juan131 ok, I just added env variable and the results...

Logs:
```console
$ docker compose up -d && docker compose logs -f --tail 50                                                                               
[+] Running 3/3
 ⠿ Network id_jenkins_default        Created                                                                                                                                                                                                                               0.1s
 ⠿ Volume "id_jenkins_jenkins_data"  Created                                                                                                                                                                                                                               0.1s
 ⠿ Container id_jenkins-jenkins-1    Started                                                                                                                                                                                                                               2.9s
id_jenkins-jenkins-1  | jenkins 15:47:52.56 
id_jenkins-jenkins-1  | jenkins 15:47:52.60 Welcome to the Bitnami jenkins container
id_jenkins-jenkins-1  | jenkins 15:47:52.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
id_jenkins-jenkins-1  | jenkins 15:47:52.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
id_jenkins-jenkins-1  | jenkins 15:47:52.61 
id_jenkins-jenkins-1  | jenkins 15:47:52.69 INFO  ==> Configuring libnss_wrapper
id_jenkins-jenkins-1  | jenkins 15:47:52.72 INFO  ==> ** Starting Jenkins setup **
id_jenkins-jenkins-1  | jenkins 15:47:52.79 DEBUG ==> Validating settings in JENKINS_* environment variables...
id_jenkins-jenkins-1  | jenkins 15:47:52.82 DEBUG ==> Moving plugins to /bitnami/jenkins/home
id_jenkins-jenkins-1  | realpath: /usr/share/jenkins/ref: No such file or directory
id_jenkins-jenkins-1  | jenkins 15:47:53.80 INFO  ==> Creating init script
id_jenkins-jenkins-1  | jenkins 15:47:53.95 INFO  ==> Starting Jenkins in background
id_jenkins-jenkins-1  | jenkins 15:47:53.96 DEBUG ==> Checking that /opt/bitnami/jenkins/logs/jenkins.log log file contains entry "Jenkins is fully up and running"
id_jenkins-jenkins-1  | jenkins 15:47:53.99 DEBUG ==> Entry "Jenkins is fully up and running" still not present in /opt/bitnami/jenkins/logs/jenkins.log (attempt 1/36)
id_jenkins-jenkins-1  | jenkins 15:48:04.33 DEBUG ==> Entry "Jenkins is fully up and running" still not present in /opt/bitnami/jenkins/logs/jenkins.log (attempt 2/36)
id_jenkins-jenkins-1  | jenkins 15:48:14.35 DEBUG ==> Entry "Jenkins is fully up and running" still not present in /opt/bitnami/jenkins/logs/jenkins.log (attempt 3/36)
id_jenkins-jenkins-1  | jenkins 15:48:24.37 DEBUG ==> Found entry "Jenkins is fully up and running" in /opt/bitnami/jenkins/logs/jenkins.log
id_jenkins-jenkins-1  | jenkins 15:48:24.46 INFO  ==> Stopping Jenkins
id_jenkins-jenkins-1  | jenkins 15:48:25.53 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
id_jenkins-jenkins-1  | jenkins 15:48:25.53 DEBUG ==> Executing /docker-entrypoint-initdb.d/csp_header.groovy
id_jenkins-jenkins-1  | jenkins 15:48:25.57 INFO  ==> Starting Jenkins in background
id_jenkins-jenkins-1  | jenkins 15:48:25.60 DEBUG ==> Checking that /opt/bitnami/jenkins/logs/jenkins.log log file contains entry "Jenkins is fully up and running"
id_jenkins-jenkins-1  | jenkins 15:48:25.61 DEBUG ==> Entry "Jenkins is fully up and running" still not present in /opt/bitnami/jenkins/logs/jenkins.log (attempt 1/36)
id_jenkins-jenkins-1  | jenkins 15:48:35.62 DEBUG ==> Found entry "Jenkins is fully up and running" in /opt/bitnami/jenkins/logs/jenkins.log
id_jenkins-jenkins-1  | jenkins 15:48:35.66 INFO  ==> Stopping Jenkins
id_jenkins-jenkins-1  | 
id_jenkins-jenkins-1  | jenkins 15:48:36.70 INFO  ==> ** Jenkins setup finished! **
id_jenkins-jenkins-1  | jenkins 15:48:36.78 INFO  ==> ** Starting Jenkins **
id_jenkins-jenkins-1  | Running from: /opt/bitnami/jenkins/jenkins.war
id_jenkins-jenkins-1  | webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.054+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @259ms to org.eclipse.jetty.util.log.JavaUtilLog
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.101+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.122+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.161+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_322-b06
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.310+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.333+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.333+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.334+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.542+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /bitnami/jenkins/home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.598+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@cd1e646{Jenkins v2.319.3,/,file:///bitnami/jenkins/home/war/,AVAILABLE}{/bitnami/jenkins/home/war}
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.611+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@3a03464{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.611+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @817ms
id_jenkins-jenkins-1  | 2022-03-05 15:48:37.611+0000 [id=23]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
id_jenkins-jenkins-1  | 2022-03-05 15:48:38.466+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
id_jenkins-jenkins-1  | 2022-03-05 15:48:38.525+0000 [id=50]	WARNING	hudson.ClassicPluginStrategy#createPluginWrapper: encountered /bitnami/jenkins/home/plugins/swarm-3.22.jpi under a nonstandard name; expected swarm.jpi
id_jenkins-jenkins-1  | 2022-03-05 15:48:38.583+0000 [id=51]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
id_jenkins-jenkins-1  | 2022-03-05 15:48:41.406+0000 [id=37]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
id_jenkins-jenkins-1  | 2022-03-05 15:48:41.412+0000 [id=47]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
id_jenkins-jenkins-1  | 2022-03-05 15:48:41.416+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.080+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.080+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.082+0000 [id=43]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.083+0000 [id=46]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.104+0000 [id=64]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.108+0000 [id=64]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 3 ms
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.173+0000 [id=38]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
id_jenkins-jenkins-1  | 2022-03-05 15:48:42.221+0000 [id=22]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

... are still not successful again. In Jenkins' scripting console, the CSP header isn't reflected yet.
![image](https://user-images.githubusercontent.com/15973840/156890842-bfa46e37-224f-4d96-97d6-41111e094bda.png)

**Comment by jmejia32** [comment]
I noticed something weird about it. After the custom script is executed, Jenkins restarts itself. Is there any reason to do this?

**Comment by juan131** [comment]
Hi @jmejia32 

Yes, Jenkins is restarted after the initialization finishes... I guess that this is problematic since any kind of customizations that aren't persisted won't be applied.
